Repository Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022, pull requests merged in 2022-10, with the labels that each got.

#33 Tailwind config colors
  .eslintrc.cjs
  tailwind.config.cjs
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#35 added and setup react router to handle routing
  package.json
  routes.jsx
  src/App.jsx
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#36 Redux setup
  .eslintrc.cjs
  package-lock.json
  package.json
  postcss.config.cjs
  src/main.jsx
  utils/services/apiConnection.js
  utils/services/appSlice.js
  utils/services/store.js
Labels: hacktoberfest-accepted, hacktoberfest

#50 code-of-conduct
  code_of_conduct.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest, no-code

#53 fix #contribution link in the readme file
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#52 created a license for the project
  LICENSE
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest, no-code, license

#77 User dashboard messages
  messages.css
  messages.css.map
  messages.html
  messages.scss
  profile avatar.png
Labels: hacktoberfest-accepted, hacktoberfest

#82 Update PhoneNumberVerification.jsx
  src/pages/PhoneNumberVerification.jsx
Labels: UI, hacktoberfest-accepted, hacktoberfest

#84 wishlist: view products on wishlist
  .github/pull_request_template.md
  images/empty.png
  images/mobile2.png
  images/wishlist.png
  public/Rectangle12.png
  public/Rectangle14.png
  public/iconGrey.png
  public/image2.png
  public/userAvatar.png
  public/wishlistIcon.png
  src/App.jsx
  src/atoms/Button/CreateWishButton.jsx
  src/atoms/Button/LogoutButton.jsx
  src/molecules/DashboardSelect.jsx
  src/molecules/NavbarDashboard.jsx
  src/molecules/SideNav.jsx
  src/molecules/SidebarDashboard.jsx
  src/pages/EmptyWishlistViewProducts.jsx
  src/pages/WishlistViewProducts.jsx
  styles/index.css
  tailwind.config.cjs
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#75 developed the entire landing page excluding the footer
  package.json
  src/App.jsx
  src/Routes.jsx
  src/images/cart-icon.svg
  src/images/chat-icon.svg
  src/images/close-icon.png
  src/images/hero_headphone.svg
  src/images/hero_keyboard.svg
  src/images/landingpage__best-quality.svg
  src/images/landingpage__client-profile-img.svg
  src/images/landingpage__meetnconnect.svg
  src/images/landingpage__p2p.svg
  src/images/landingpage__support.svg
  src/images/landingpage__wavy-arrow.svg
  src/images/landingpage__wavy-dashed.svg
  src/images/landingpage__wavy-underline.svg
  src/images/menu-icon.svg
  src/images/product-controller.png
  src/images/product-keyboard.png
  src/molecules/Home.jsx
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#88 added the pop up sucess message to the user dashboard: add new produc…
  src/AddNewProduct/components/AddNewProductSucessPopUp.jsx
  src/AddNewProduct/components/Input.jsx
  src/AddNewProduct/components/Overlay.jsx
  src/AddNewProduct/icons/success.svg
  src/AddNewProduct/pageOne/AddNewProductPage1.jsx
  src/App.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#90 Authentication: Kyc UI
  package.json
  src/App.jsx
  src/component/kyc-page/Kyc.jsx
  src/component/kyc-page/assets/downArrow.svg
  src/component/kyc-page/assets/hamburger.svg
  src/component/kyc-page/assets/kyc-img.svg
  src/component/kyc-page/assets/line.svg
  src/component/kyc-page/assets/logo.svg
  src/component/kyc-page/kyc.css
  vite.config.js.timestamp-1665269581924.mjs
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#94 Create Account UI
  package-lock.json
  package.json
  routes.jsx
  src/App.jsx
  src/Routes.jsx
  src/molecules/Home.jsx
  src/pages/create-account/CreateAccount.jsx
  src/pages/create-account/images/Facebook.svg
  src/pages/create-account/images/Google.svg
  src/pages/create-account/images/Hide.svg
  src/pages/create-account/images/Line.svg
  src/pages/create-account/images/Main.svg
  src/pages/create-account/images/Menu-Full.svg
  tailwind.config.cjs
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#81 delete product
  issue_template.md
  package-lock.json
  package.json
  public/images/33.png
  public/images/Chat.png
  public/images/Group.png
  public/images/I4G-OPENSOURCE-IMAGE.jpg
  public/images/Vector2.png
  public/images/bar.png
  public/images/box.png
  public/images/element-4.png
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/ipadLogo.png
  public/images/logo.png
  public/images/logout.png
  public/images/notification.png
  public/images/person.png
  public/images/search.png
  public/images/trash-can.png
  public/images/web.png
  public/images/wishlist.png
  src/AddNewProduct/components/DragNDrop.jsx
  src/AddNewProduct/components/Input.jsx
  src/AddNewProduct/components/Navbar.jsx
  src/AddNewProduct/components/SideBar.jsx
  src/App.jsx
  src/Routes.jsx
  src/delete/context.jsx
  src/delete/data.jsx
  src/delete/delete.jsx
  src/delete/deleteProduct.jsx
  src/delete/hero.jsx
  src/delete/modal.jsx
  src/delete/sidebar.jsx
  src/main.jsx
  styles/index.css
  tailwind.config.cjs
  yarn.lock
Labels: hacktoberfest-accepted

#76 Implemented view product page(empty)- first page of #18
  public/fonts/CabinetGrotesk-Regular.otf
  public/fonts/Campton-LightDEMO.otf
  src/App.jsx
  src/assets/Chat.png
  src/assets/Vector.png
  src/assets/Vector1.png
  src/assets/Vector2.png
  src/assets/_.png
  src/assets/avatar.png
  src/assets/box.png
  src/assets/delete.png
  src/assets/edit.png
  src/assets/element-4.png
  src/assets/img1.png
  src/assets/img2.png
  src/assets/img3.png
  src/assets/img4.png
  src/assets/logos_parcel-icon.png
  src/assets/logout.png
  src/assets/notification.png
  src/assets/search-normal.png
  src/products-view/ProductDesktop.jsx
  src/products-view/ProductMobile.jsx
  src/products-view/Products.jsx
  src/products-view/ProductsCard.jsx
  styles/index.css
  utils/services/appSlice.js
  utils/services/store.js
  vite.config.js.timestamp-1665269581924.mjs
Labels: hacktoberfest-accepted, hacktoberfest

#86 moved help page to pages directory
  package.json
  src/App.jsx
  src/Routes.jsx
  src/images/martZ.svg
  src/pages/Help.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#121 Added New Pull Request project structure and style guide to CONTRIBUTING.md
  CONTRIBUTING.md
  style_guide.md
Labels: hacktoberfest-accepted, hacktoberfest

#119 Forget Password UI
  src/App.jsx
  src/component/forgotPasswordPage/ForgotPassword.jsx
  src/component/forgotPasswordPage/forgotPass.css
  src/component/forgotPasswordPage/girl-photo.svg
  src/component/forgotPasswordPage/hamburger.svg
  src/component/forgotPasswordPage/line.svg
  src/component/forgotPasswordPage/logo.svg
Labels: hacktoberfest-accepted, hacktoberfest

#145 add-success-and-edit-pop-up-message
  public/images/success.png
  src/delete/context.jsx
  src/delete/data.jsx
  src/delete/delete.jsx
  src/delete/deleteProduct.jsx
  src/delete/hero.jsx
  src/delete/modal.jsx
  src/delete/sidebar.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#148 added more details about submitting changes
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest, no-code

#147 Techmart Userflow
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, no-code

#155 Design Style Guide
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest

#156 Landing Page Design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, no-code, design

#158 Developed Reset Password and Reset Password Success
  src/App.jsx
  src/Routes.jsx
  src/assets/images/HideIcon.png
  src/assets/images/empty.png
  src/assets/images/laptop-woman.png
  src/assets/images/mobile2.png
  src/assets/images/success-avatar.png
  src/assets/images/wishlist-icon.png
  src/assets/images/wishlist.png
  src/components/atoms/Button/ProceedToLoginButton.jsx
  src/components/atoms/Button/SubmitButton.jsx
  src/components/atoms/DragNDrop.jsx
  src/components/molecules/PasswordResetForm.jsx
  src/components/molecules/PasswordResetSuccessPopup.jsx
  src/components/molecules/SideNav.jsx
  src/components/molecules/SidebarDashboard.jsx
  src/components/molecules/sidebar.jsx
  src/pages/EmptyWishlistViewProducts.jsx
  src/pages/PasswordResetPage.jsx
  src/pages/WishlistViewProducts.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#177 Add Dashboard Layout to project
  src/Routes.jsx
  src/assets/data/data.jsx
  src/components/molecules/NavbarDashboard.jsx
  src/components/molecules/SideBar.jsx
  src/components/molecules/SideNav.jsx
  src/components/molecules/SidebarDashboard.jsx
  src/components/molecules/sidebar.jsx
  src/pages/AddNewProductPage1.jsx
  src/pages/CreateAccount.jsx
  src/pages/EmptyWishlistViewProducts.jsx
  src/pages/Help.jsx
  src/pages/PasswordResetPage.jsx
  src/pages/WishlistViewProducts.jsx
  src/templates/AdminDashBoardLayout.jsx
  src/unknown code/messages.css
  src/unknown code/messages.css.map
  src/unknown code/messages.html
  src/unknown code/messages.scss
  src/unknown code/support.css
  src/unknown code/support.css.map
  src/unknown code/support.html
  src/unknown code/support.scss
Labels: hacktoberfest-accepted, hacktoberfest, Admin

#168 Improved Landing Page UX Writing
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#184 Improve Visual Hierachy and Alignment on the Landing Page
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#192 Design Authentication Screens (Create an Account)
  Design.md
Labels: hacktoberfest, design

#197 UX Writing for Authentication Screens
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#200 Design User Dashboard: Home
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#189 Developed user dashboard home UI.
  src/App.jsx
  src/Routes.jsx
  src/assets/icons/CloseSquare.svg
  src/assets/icons/ProfileIcon.svg
  src/assets/images/Rectangle-14GamePad.png
  src/assets/images/dashboard-banner.png
  src/assets/images/image-2macbook.png
  src/components/atoms/Button/AddToWishBtn.jsx
  src/components/atoms/Button/MessageSellerButton.jsx
  src/components/molecules/NavbarDashboard.jsx
  src/components/molecules/PasswordResetForm.jsx
  src/components/molecules/ProductDetailsPopup.jsx
  src/components/molecules/SidebarDashboard.jsx
  src/components/molecules/SidebarWishlist.jsx
  src/components/molecules/UserDashboardSideMenu.jsx
  src/pages/DashboardPage.jsx
  src/pages/EmptyWishlistViewProducts.jsx
  src/pages/PasswordResetPage.jsx
  src/pages/WishlistViewProducts.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#201 I Improved The UX Writing On The Authentication screens
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#208 Design terms of service and the privacy policy page for the landing page
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#210 added messages empty page
  src/Routes.jsx
  src/assets/images/no-messages.png
  src/pages/MessagesEmpty.jsx
Labels: hacktoberfest-accepted

#213 User Dashboard: View Uploaded Products Screen
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#214 User dashboard ( Product upload page)
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#215 User Dashboard: Help & Support
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#219 Improve UX writing of Legal Policy Statement
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#222 I designed the Search Result Screen on the User Dashboard
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#227 Design select and delete product on wishlist
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#220 Homepage optimisation + footer
  src/assets/icons/footer-fb.svg
  src/assets/icons/instagram.svg
  src/assets/icons/linkedin.svg
  src/assets/icons/twitter.svg
  src/assets/icons/up-arrow.svg
  src/assets/images/landingpage-hero-clipart-left.svg
  src/assets/images/landingpage-hero-clipart-right.svg
  src/pages/Home.jsx
  src/pages/home.css
Labels: hacktoberfest-accepted, hacktoberfest

#229 Design a user profile page
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#232 Added my contribution on UI design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#233 Added my contribution to UI Design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#234 Added my contribution to UI Design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#235 Added my contributions to the UI Design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#237 Added my contributions to the UI Design
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#246 Addition of Side Navigation for User Dashboard - Mobile Closes Issue #139
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#247 Added sliding customer review section using swiper.js
  package-lock.json
  package.json
  src/pages/Home.jsx
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest, Admin

#249 Design of Side Navigation for Admin Dashboard - Desktop
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#250 Design of Side Navigation for Admin Dashboard - Tablet
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#252 Developed Create sub admin and Sub admin profile pages
  src/Routes.jsx
  src/assets/data/data.jsx
  src/assets/icons/arrowLeft.svg
  src/assets/icons/plusIcon.svg
  src/assets/icons/userIconBlue.svg
  src/assets/icons/usersIcon.svg
  src/components/atoms/Button/WarningButton.jsx
  src/components/molecules/AdminSideMenu.jsx
  src/components/molecules/CreateSubAdminErrorPopup.jsx
  src/components/molecules/CreateSubAdminSuccessPopup.jsx
  src/components/molecules/NavbarAdmin.jsx
  src/components/molecules/PersonalInfoForm.jsx
  src/components/molecules/ProductDetailsPopup.jsx
  src/components/molecules/SideBar.jsx
  src/components/molecules/SubAdminCreatePasswordForm.jsx
  src/components/molecules/SubAdminDetailsSentSuccess.jsx
  src/pages/CreateSubAdmin.jsx
  src/pages/SubAdminProfile.jsx
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest, Admin

#143 Phone Number Verification Successfull
  public/images/45.png
  src/App.jsx
  src/molecules/modal/PhoneNumberVerificationSuccessfullUI.jsx
  src/pages/PhoneNumberVerification.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#225 developed 404 page
  src/Routes.jsx
  src/assets/images/rafiki.svg
  src/pages/404.jsx
  src/pages/Help.jsx
  src/pages/Home.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#257 Admin suspend popups
  src/App.jsx
  src/components/molecules/AdminSuspendAccountPopup.jsx
  src/components/molecules/AdminSuspendAccountSuccessfullPopup.jsx
  src/components/molecules/AdminSuspendFail.jsx
Labels: hacktoberfest-accepted, hacktoberfest, Admin

#312 add inline tailwind styles for buttons behaviour on hover and click
  src/components/atoms/SecondaryButton.jsx
  src/pages/CreateAccount.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#291 Admin delete account popups
  public/images/33.png
  src/Routes.jsx
  src/components/molecules/AdminDeleteAccountFailPopup.jsx
  src/components/molecules/AdminDeleteAccountPopup.jsx
  src/components/molecules/AdminDeleteAccountSuccessfullPopup.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#260 Enhance and optimise the authentication page
  src/Routes.jsx
  src/assets/images/main.svg
  src/components/atoms/AuthSide.jsx
  src/components/atoms/Button/ProceedToLoginButton.jsx
  src/components/molecules/NavHome.jsx
  src/components/molecules/NavbarDashboard.jsx
  src/components/molecules/Overlay.jsx
  src/components/molecules/PasswordResetForm.jsx
  src/components/molecules/PasswordResetSuccessPopup.jsx
  src/components/molecules/UserDashboardSideMenu.jsx
  src/pages/CreateAccount.jsx
  src/pages/EmailVerify.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Home.jsx
  src/pages/Kyc.jsx
  src/pages/Login.jsx
  src/pages/PasswordResetPage.jsx
  src/pages/PhoneNumberVerification.jsx
  src/pages/style.css
  yarn.lock
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#329 Design of the admin dashboard : Home(desktop view)
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#294 Admin product page
  src/Routes.jsx
  src/assets/icons/33.png
  src/assets/icons/circular-check.png
  src/components/atoms/AuthSide.jsx
  src/components/atoms/Button/Decline.jsx
  src/components/atoms/Button/Proceed.jsx
  src/components/molecules/AddNewProductSucessPopUp.jsx
  src/components/molecules/AdminDeleteAccountFailPopup.jsx
  src/components/molecules/AdminDeleteAccountPopup.jsx
  src/components/molecules/AdminDeleteAccountSuccessfullPopup.jsx
  src/components/molecules/CreateSubAdminErrorPopup.jsx
  src/components/molecules/DeleteConfirmation.jsx
  src/components/molecules/MessagesHeader.jsx
  src/components/molecules/NavHome.jsx
  src/components/molecules/SideBar.jsx
  src/components/molecules/modal.jsx
  src/components/molecules/sidebar.jsx
  src/pages/AdminUsersProfile.jsx
  src/pages/AdminUsersProfileWithProducts.jsx
  src/pages/CreateSubAdmin.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Home.jsx
  src/pages/SubAdminList.jsx
  src/pages/SubAdminProfile.jsx
  src/pages/SuspendedUsersList.jsx
  src/pages/UserList.jsx
  src/pages/Users.jsx
  src/pages/admin/messages/MessagesChat.jsx
  src/pages/admin/messages/MessagesEmpty.jsx
  src/pages/admin/messages/MessagesStart.jsx
  src/pages/admin/product/DeleteProductModal.jsx
  src/pages/admin/product/MakeProductUnavailable.jsx
  src/pages/admin/product/ProductDetails.jsx
  src/pages/admin/product/index.jsx
  src/pages/admin/product/index.module.css
  src/pages/admin/users/AdminUsersProfile.jsx
  src/pages/admin/users/AdminUsersProfileWithProducts.jsx
  src/pages/admin/users/CreateSubAdmin.jsx
  src/pages/admin/users/SubAdminList.jsx
  src/pages/admin/users/SubAdminProfile.jsx
  src/pages/admin/users/SuspendedUsersList.jsx
  src/pages/admin/users/UserList.jsx
  src/pages/admin/users/index.jsx
  src/pages/delete-d
  src/templates/AdminDashBoardLayout.jsx
  styles/index.css
  utils/services/appSlice.js
Labels: hacktoberfest-accepted, hacktoberfest

#314 added the terms and policy pages
  src/Routes.jsx
  src/components/atoms/TermsAndPolicyNav.jsx
  src/components/molecules/Footer.jsx
  src/components/molecules/MainNav.jsx
  src/components/molecules/Terms.jsx
  src/pages/Home.jsx
  src/pages/Policy.jsx
  src/pages/TermsOfSevice.jsx
  styles/terms.css
Labels: hacktoberfest-accepted, hacktoberfest

#333 fix sidebar layout
  src/components/molecules/SideBar.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#372 Add animations on scroll
  package-lock.json
  package.json
  src/pages/Home.jsx
  yarn.lock
Labels: hacktoberfest

#388 UX writing on Authentication Screen (Email notification)
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#389 Designed admin message page Closes #
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#391 UX writing on Authentication Screen (Reset Password)
  Design.md
Labels: hacktoberfest-accepted, hacktoberfest, design

#390 Dashboard notifications
  src/components/molecules/DashboardNotificationModal.jsx
  src/pages/DashboardPage.jsx
  src/pages/style.css
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#412 Admin Dashboard
  package.json
  src/Routes.jsx
  src/assets/data/AdminDashboardData.jsx
  src/assets/icons/chevron-down.svg
  src/assets/icons/dashboard-blue.svg
  src/assets/icons/optionsIcon.svg
  src/assets/icons/total-products.svg
  src/assets/icons/total-users.svg
  src/assets/images/avatar7.png
  src/assets/images/item1.png
  src/assets/images/item2.png
  src/assets/images/item3.png
  src/assets/images/item4.png
  src/components/molecules/AdminAnalyticsDropdown.jsx
  src/components/molecules/AdminDaysDropdown.jsx
  src/components/molecules/AdminMonthsDropdown.jsx
  src/components/molecules/AdminMoreOptions.jsx
  src/components/molecules/AdminSortByDropdown.jsx
  src/components/molecules/AdminTopGreeting.jsx
  src/components/molecules/DeleteProductConfirmation.jsx
  src/components/molecules/ProductDetailsPopup.jsx
  src/components/molecules/SideBar.jsx
  src/pages/AdminDashboard.jsx
  src/pages/AdminEmptySearchResult.jsx
  src/pages/ProductSearchReslts.jsx
  src/pages/SearchProductsByUser.jsx
  src/pages/UserSearchResults.jsx
  src/templates/AdminDashBoardLayout.jsx
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#416 feature: ```redirect to home``` when click on techmart logo
  src/components/molecules/NavHome.jsx
  src/pages/Home.jsx
Labels: hacktoberfest-accepted, hacktoberfest
